# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c2dc8a3a5bc17e719a912eabaf428470322f3f454d3d332dff7e18799d98d15565d1f37fbc909e4621396e6f3d97869713c8306636b116a993aefb26372a96a3

test:
  secret_key_base: a888dde45ae412380031e0616fea7f7271491fe1794b7dadfec1aaf672eeb290de7cc855e964889544bccbfacc504a4c74988f45746b2bdc02dfaf6f3671f59e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
