const MovieActionTypes = {
	HANDLE_ERROR: 'HANDLE_ERROR',
	GET_ALL: 'GET_ALL',
	GET_ALL_RESPONSE: 'GET_ALL_RESPONSE',
	GET_BY_ID: 'GET_BY_ID',
	GET_BY_ID_RESPONSE: 'GET_BY_ID_RESPONSE',
	EDIT_MOVIE: 'EDIT_MOVIE',
	EDIT_MOVIE_RESPONSE: 'EDIT_MOVIE_RESPONSE',
	DELETE_MOVIE: 'DELETE_MOVIE',
	DELETE_MOVIE_RESPONSE: 'DELETE_MOVIE_RESPONSE',
	ADD_MOVIE: 'ADD_MOVIE',
	ADD_MOVIE_RESPONSE: 'ADD_MOVIE_RESPONSE'
};

export default MovieActionTypes;
